name: Generate Sitemap

on:
  push:
    branches: [ main ]

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Wait for GitHub Pages to update
      run: sleep 120
    
    - name: Generate sitemap
      run: npx sitemap-generator-cli https://bamtu.github.io
    
    - name: Commit and push sitemap
      run: |
        git config --local user.email "59360@naver.com"
        git config --local user.name "bamtu"
        git add sitemap.xml
        if git diff --staged --quiet; then
          echo "No changes to sitemap.xml"
        else
          git commit -m "Auto-update sitemap.xml [skip ci]"
          git push
        fi
    # GitHub Pages 재배포 강제 트리거
    - name: Trigger GitHub Pages build
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pages/builds