name: Generate Sitemap

on:
  push:
    branches: [ main ]

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Wait for GitHub Pages to update
      run: sleep 60
    
    - name: Generate sitemap
      run: npx sitemap-generator-cli https://bamtu.github.io
    
    - name: Commit and push sitemap
      run: |
        git config --local user.email "59360@naver.com"
        git config --local user.name "bamtu"
        git add sitemap.xml
        if git diff --staged --quiet; then
          echo "No changes to sitemap.xml"
        else
          git commit -m "Auto-update sitemap.xml"
          git push
        fi
    
    - name: Trigger Pages deployment with gh CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 최신 커밋으로 Pages 빌드 요청
        gh api repos/${{ github.repository }}/pages/builds --method POST || true
        
        # 또는 워크플로우 디스패치로 다른 방법 시도
        sleep 10
        git commit --allow-empty -m "Force Pages rebuild"
        git push


      