name: Generate xml sitemap

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://bamtu.github.io/
          path-to-root: _site  # Jekyll 빌드 결과물 폴더 지정
          include-html: true
          
      - name: Commit and push sitemap
        run: |
          if [[ `git status --porcelain sitemap.xml` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add sitemap.xml
            git commit -m "Automated sitemap update"
            git push
          fi
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Gems
        run: bundle install

      - name: Build the site
        run: bundle exec jekyll build --destination ./_site

      # - name: Set up SSH deploy key
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/deploy_key
      #     chmod 600 ~/.ssh/deploy_key
      #     eval "$(ssh-agent -s)"
      #     ssh-add ~/.ssh/deploy_key
      #   env:
      #     ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     publish_dir: ./_site
      #   env:
      #     ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}